# Generated by Django 3.2.5 on 2021-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bloguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(default='static/media/avatar/default.png', upload_to='static/media/avatar'),
        ),
    ]
