# Generated by Django 3.2.5 on 2021-08-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_name',
            field=models.ManyToManyField(to='article.Tag'),
        ),
    ]
