# Generated by Django 3.2.5 on 2021-08-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='number_with_this',
            field=models.IntegerField(default=0),
        ),
    ]
