# Generated by Django 3.2.5 on 2021-08-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_comment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
