# Generated by Django 3.2.5 on 2021-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210815_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_num',
            field=models.IntegerField(default=0),
        ),
    ]
