# Generated by Django 3.2.5 on 2021-08-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_article_view_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='view_num',
            new_name='page_view',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.CreateModel(
            name='BrowseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('time', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
