# Generated by Django 3.2.5 on 2021-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_HTML',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='number_with_this',
            field=models.IntegerField(default=0),
        ),
    ]
