# Generated by Django 3.2.5 on 2021-08-28 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_auto_20210828_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='toUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='toUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
